[package]
name = "bad-grep"
version = "0.1.1"
authors = ["S-Mann"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "~2"
clap = {version = "~2.33.3", features = ["yaml"]}